#!/bin/sh

# change to video player of choice
vplay="mpv"

# change to youtube or invidious instance of choice
instance="https://youtube.com/watch?v="

# set to dmenu or fzf
menu="fzf"

vid=$(echo "$*" | sed 's/ /+/g')

[ -z "$vid" ] && exit

api=$(curl -s https://vid.puffyan.us/api/v1/search/?q="$vid")
author=$(echo "$api" | jq | grep -w "author" | sed 's/[":,]//g' | cut -c 12-)
title=$(echo "$api" | jq | grep "title" | cut -c 12-)
id=$(echo "$api" | jq | grep "videoId" | sed 's/[,:"]//g' | cut -c 13-)
tfile=~/.cache/yttitles
idfile=~/.cache/ytidis
afile=~/.cache/ytauthor

rm "$tfile"
rm "$idfile"
rm "$afile"
echo "$id" >> $idfile
echo "$title" >> $tfile
echo "$author" >> $afile

paste $afile  $tfile > ~/.cache/ytsh

if [ $menu = "fzf"  ]; then
	choice=$(fzf --layout=reverse < ~/.cache/ytsh)
else
	choice=$(dmenu -l 12 < ~/.cache/ytsh)
fi

[ -z "$choice" ] && exit

choice=$(echo "$choice" | sed 's/.*://')
line=$(grep -n "$choice" $tfile | awk '{print $1}' | sed 's/[:]//g')
$vplay "$instance$(sed -n "${line}p" $idfile)"
