#!/bin/bash

# change to video player of choice
vplay="mpv"
# change to youtube or invidious instance of choice
instance="https://youtube.com/watch?v="
vid=$(echo $* | sed 's/ /+/g')
if [ -z $vid ]; then 
	exit 
fi
api=$(curl -s https://vid.puffyan.us/api/v1/search/?q=$vid)
author=$(echo "$api" | jq | grep -w "author" | sed 's/[":,]//g' | cut -c 12-)
title=$(echo "$api" | jq | grep "title" | cut -c 12-)
id=$(echo "$api" | jq | grep "videoId" | sed 's/[,:"]//g' | cut -c 13-)
tfile=~/.cache/yttitles
idfile=~/.cache/ytidis
afile=~/.cache/ytauthor

rm $tfile &> /dev/null
rm $idfile &> /dev/null
rm $afile &> /dev/null
echo "$id" >> $idfile
echo "$title" >> $tfile
echo "$author" >> $afile
pr -tmJ $afile  $tfile > ~/.cache/ytsh
choice=$(cat ~/.cache/ytsh | fzf --layout=reverse)
if [ -z $choice ]; then 
	exit 
fi
choice=$(echo "$choice" | sed 's/.*://')
line=$(grep -n "$choice" $tfile | awk '{print $1}' | sed 's/[:]//g')
echo $line
sleep 4
$vplay "$instance$(sed -n "${line}p" $idfile)"
