#!/bin/bash

# change to video player of choice
vplay="mpv"
# change to youtube or invidious instance of choice
instance="https://youtube.com/watch?v="
vid=$(echo $* | sed 's/ /+/g')
if [ -z $vid ]; then 
	exit 
fi
api=$(curl -s https://vid.puffyan.us/api/v1/search/?q=$vid)
#channel=$(echo "$api" | jq | grep -w "author" | cut -c 15- | sed 's/[":,]//g')
title=$(echo "$api" | jq | grep "title" | cut -c 12-)
id=$(echo "$api" | jq | grep "videoId" | sed 's/[,:"]//g' | cut -c 13-)
tfile=~/.cache/yttitles
idfile=~/.cache/ytids

rm $tfile &> /dev/null
rm $idfile &> /dev/null
echo "$id" >> $idfile
echo "$title" >> $tfile
choice=$(echo "$title" | fzf --layout=reverse)
if [ -z $choice ]; then 
	exit 
fi
line=$(grep -n "$choice" $tfile | awk '{print $1}' | sed 's/[:]//g')
$vplay "$instance$(sed -n "${line}p" $idfile)"
